name: iiitd_mentorship
description: Connect with IIITD alumni through Alumni Mentorship platform. Discover mentors, schedule meetings, and get advice on your career path.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_calendar: 23.1.43
  image_picker: 1.0.4
  # latest version of mockito
  mockito: 
  build_runner: ^2.4.6
  rxdart: ^0.27.7
  url_launcher: 


  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  firebase_storage: ^11.2.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.13.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.14.0

dev_dependencies:
  flutter_launcher_icons: 
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
      - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
